name: Main

on:
  # trigger on push to main branch, except tags
  push:
     branches:
       - main
     tags-ignore:
       - '**'

  # trigger on pull request to main branch
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    # only run on pull request
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  commits:
    name: Check commits
    runs-on: ubuntu-latest

    # only run on pull request
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ref: ${{ github.event.pull_request.head.sha }}

      - name: Install commitizen-tools
        run : |
          pip install --user -U Commitizen

      - name: Check commits
        run: |
          cz check --rev-range origin/main..origin/${{ github.head_ref }}

  release:
    name: Release
    runs-on: ubuntu-latest

    # only run on push to main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # give permissions to write to the repository
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          # set "Allow GitHub Actions to create and approve pull requests" under repository Settings > Actions > General
          # https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions

          # a PAT is required to trigger workflows (tests and commits jobs from above) on release pull requests
          # https://github.com/googleapis/release-please-action?tab=readme-ov-file#github-credentials
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
